classdef Cell < edu.washington.riekelab.sara.sources.Cell
    
    methods
        
        function obj = Cell()
            import symphonyui.core.*;
            
            obj.addProperty('type', 'unknown', ...
                'type', PropertyType('char', 'row', containers.Map( ...
                    {'unknown', 'RGC', 'amacrine', 'bipolar', 'horizontal', 'photoreceptor'}, ...
                    {{}, ...
                    {'ON midget', 'OFF midget', 'ON-parasol', 'OFF parasol', 'small bistratified','ON smooth monostratified','OFF smooth monostratified', 'ON', 'OFF', 'ON-OFF', 'melanopsin'}, ...
                    {'AII', 'A17', 'ON-starburst', 'ON-wiry', 'OFF-wiry', 'ON', 'OFF', 'ON-OFF'}, ...
                    {'OFF-diffuse', 'OFF-midget', 'ON-diffuse', 'ON-midget', 'rod'}, ...
                    {}, ...
                    {'S cone', 'M cone', 'L cone', 'rod'}})), ...
                'description', 'The confirmed type of the recorded cell');
            
            obj.addProperty('XLocation', '',...
                'Description', 'X-axis location of cell');
            obj.addProperty('YLocation', '',...
                'Description', 'Y-axis location of cell');
            
            % cone-specific properties
            obj.addProperty('center', 'unknown',...
                'center', PropertyType('char', 'row',...
                    {'unknown', 'L', 'M', 'LM', 'LS', 'MS', 'LMS'}),...
                'description', 'Center cone type(s)');
            obj.addProperty('surround', 'unknown',...
                'type', PropertyType('char', 'row',...
                    {'unknown', 'L', 'M', 'S', 'LM', 'LS', 'MS', 'LMS'}),...
                'description', 'surround cone type(s)');
            obj.addProperty('SConeInput','unknown',...
                'SConeInput', PropertyType('char', 'row',...
                    {'unknown', 'yes', 'no'}),...
                'description', 'Does the cell have s-cone input');
            obj.addProperty('centerCones', int32(0),...
                'Type', PropertyType('int32', 'scalar', [0 100]),...
                'Description', 'How many center cones?');
            
            obj.addAllowableParentType('edu.washington.riekelab.sara.sources.primate.Preparation');
        end
        
    end
    
end

