classdef Input < edu.washington.riekelab.sara.sources.Input

	methods
		function obj = Input()
			import symphonyui.core.*;

			obj.addProperty('type', '',...
				'type', PropertyType('char', 'row', containers.Map(...
					{'', 'cone', 'bipolar'},...
					{...
						{},...
						{'unknown', 'S-cone', 'M-cone', 'L-cone'},...
						{}...
					})),...
				'description', 'The targeted upstream input');
            obj.addProperty('xlocation', '', ...
                'description', 'Center location on x-axis');
            obj.addProperty('ylocation', '', ...
            	'description', 'Center location on y-axis');
            obj.addProperty('radius', '', ...
            	'description', 'Radius of targeted input');

			obj.addAllowableParentType('edu.washington.riekelab.sara.sources.primate.Cell');
		end
	end
end 