set(0, 'DefaultAxesFontName', 'Roboto',...
  'DefaultAxesTitleFontWeight', 'normal',...
  'DefaultFigureColor', 'w',...
  'DefaultAxesBox', 'off',...
  'DefaultLegendEdgeColor', 'w',...
  'DefaultAxesTickDir', 'out');
