function fh = myfigure
    fh = figure('Color', 'w');
    set(gca, 'FontName', 'Roboto',...
        'TitleFontWeight', 'normal',...
        'Box', 'off',...
        'DefaultLegendEdgeColor', 'w',...
        'DefaultLegendFontSize', 10,...
        'TickDir', 'out');

